services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true # ← لتفعيل auto deploy عند كل push إلى GitHub
    envVars:
      # إعدادات Laravel العامة
      - key: APP_ENV
        value: "production"
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://your-app-name.onrender.com"

      # إعدادات قاعدة البيانات
      - key: DB_CONNECTION
        value: "mysql"
      - key: DB_HOST
        value: "your-db-host"
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: "your-database"
      - key: DB_USERNAME
        value: "your-user"
      - key: DB_PASSWORD
        value: "your-password"

      # إعدادات SendGrid
      - key: MAIL_MAILER
        value: "smtp"
      - key: MAIL_HOST
        value: "smtp.sendgrid.net"
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        value: "apikey" # ← حرفيًا "apikey"
      - key: MAIL_PASSWORD
        sync: false # ← خزّنها من Render Dashboard يدويًا (آمن أكثر)
      - key: MAIL_ENCRYPTION
        value: "tls"
      - key: MAIL_FROM_ADDRESS
        value: "you@example.com"
      - key: MAIL_FROM_NAME
        value: "Your App Name"
